version: "3"
services:
  alist: # 分布式文件管理工具
    image: xhofe/alist
    container_name: alist
    volumes:
      - /mnt/sda/config/alist:/opt/alist/data
    ports:
      - 5244:5244
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m" # 限制docker控制台日志大小，可自行调整
    networks:
      - media

  qbittorrent: # 下载器
    image: superng6/qbittorrentee
    container_name: qbittorrent
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      - /mnt/sda/config/qbittorrent:/config
      - /mnt/sda/downloads:/downloads
      - /mnt/sda/media:/media
    environment:
      - WEBUIPORT=8080
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m" # 限制docker控制台日志大小，可自行调整
    networks:
      - media

  jackett: # 种子索引器
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - /mnt/sda/config/jackett:/config
      - /mnt/sda/downloads:/downloads
    environment:
      - AUTO_UPDATE=true
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m" # 限制docker控制台日志大小，可自行调整
    networks:
      - media

  jellyfin: # 媒体挂削器
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - /mnt/sda/config/jellyfin/config:/config
      - /mnt/sda/config/jellyfin/cache:/cache
      - /mnt/sda/media:/media
    environment:
      - WEBUIPORT=8080
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    devices:
      - /dev/dri:/dev/dri
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m" # 限制docker控制台日志大小，可自行调整
    networks:
      - media
    depends_on:
      - alist
      - qbittorrent
      - jackett

  chinesesubfinder: # 中文字幕监控器
    image: allanpk716/chinesesubfinder
    container_name: chinesesubfinder
    volumes:
      - /mnt/sda/config/chinesesubfinder/config:/config
      - /mnt/sda/media:/media # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      - /mnt/sda/config/chinesesubfinder/browser:/root/.cache/rod/browser # 容器重启后无需再次下载 chrome，除非 go-rod 更新
    environment:
      - PUID=1000 # uid
      - PGID=1000 # gid
      - PERMS=true
      - TZ=Asia/Shanghai # 时区
    restart: always
    ports:
      - 19035:19035 # 从0.20.0版本开始，通过webui来设置
      - 19037:19037 # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
      driver: "json-file"
      options:
        max-size: "1m" # 限制docker控制台日志大小，可自行调整
    networks:
      - media
    depends_on:
      - jellyfin

  radarr: # 电影监控器
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - /mnt/sda/config/radarr:/config
      - /mnt/sda/media:/media
      - /mnt/sda/downloads:/downloads
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m" # 限制docker控制台日志大小，可自行调整
    networks:
      - media
    depends_on:
      - alist
      - qbittorrent
      - jackett

  sonarr: # 电视剧监控器
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - /mnt/sda/config/sonarr:/config
      - /mnt/sda/media:/media
      - /mnt/sda/downloads:/downloads
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m" # 限制docker控制台日志大小，可自行调整
    networks:
      - media
    depends_on:
      - alist
      - qbittorrent
      - jackett

networks:
  media:
