version: "3"
services:
  alist:
    image: xhofe/alist
    volumes:
      - /mnt/sda/config/alist:/opt/alist/data
    ports:
      - 5244:5244
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: always
    networks:
      - media

  qbittorrent:
    image: superng6/qbittorrentee
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    volumes:
      - /mnt/sda/config/qbittorrent:/config
      - /mnt/sda/downloads:/downloads
      - /mnt/sda/media:/media
    environment:
      - WEBUIPORT=8080
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: always
    networks:
      - media

  jackett:
    image: linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - /mnt/sda/config/jackett:/config
      - /mnt/sda/downloads:/downloads
    environment:
      - AUTO_UPDATE=true
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: always
    networks:
      - media

  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - 8096:8096
    volumes:
      - /mnt/sda/config/jellyfin/config:/config
      - /mnt/sda/config/jellyfin/cache:/cache
      - /mnt/sda/media:/media
    environment:
      - WEBUIPORT=8080
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    devices:
      - /dev/dri:/dev/dri
    restart: always
    networks:
      - media
    depends_on:
      - alist
      - qbittorrent
      - jackett

  radarr:
    image: linuxserver/radarr
    ports:
      - 7878:7878
    volumes:
      - /mnt/sda/config/radarr:/config
      - /mnt/sda/media:/media
      - /mnt/sda/downloads:/downloads
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: always
    networks:
      - media
    depends_on:
      - alist
      - qbittorrent
      - jackett

  sonarr:
    image: linuxserver/sonarr
    ports:
      - 8989:8989
    volumes:
      - /mnt/sda/config/sonarr:/config
      - /mnt/sda/media:/media
      - /mnt/sda/downloads:/downloads
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
    restart: always
    networks:
      - media
    depends_on:
      - alist
      - qbittorrent
      - jackett

networks:
  media:
